services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack:3.0.0
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=sqs,dynamodb,s3
      - AWS_DEFAULT_REGION=af-south-1